[package]
name = "vfdm-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "vfdm desktop app"

[lib]
name = "vfdm_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
vfdm-engine = { path = "../../../crates/vfdm-engine" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hex = "0.4"
subtle = "2"
